#!groovy

def provisioner() {
  stage('Checkout') {
    checkout scm
  }

  stage('Build Environment Space') {
    sh "cf orgs"
  }

  stage('Secure Environment Space') {
      sh "ls"
      sh """#!/bin/bash
          set -x
          pwd
        """
  }

}

node('Chef Provisioner Prod') {
  provisioner()
}
