#!groovy

def provisioner() {
  stage('Checkout Environment Definition') {
    checkout scm
  }

  stage('Allocate Stage Environment') {
  sh """#!/bin/bash -x
      cf orgs
    """
  }

  stage('Connect to Stage Environment') {
  sh """#!/bin/bash -x
      cf target -o cyber
    """
  }

  stage('Manage/Update Environment space-quotas') {
    sh """#!/bin/bash -x
      cf space-quotas
      """
  }

  stage('Build Stage Environment Space') {
  sh """#!/bin/bash -x
      cf orgs
    """
  }

  stage('Secure Stage Environment: Security Groups') {
      sh """#!/bin/bash -x
          cf spaces
        """
  }

  stage('Secure Stage Environment: Assign Space Manager') {
      sh """#!/bin/bash -x
          cf spaces
        """
  }

}

node('Chef Provisioner Prod') {
  provisioner()
}
